export const ADD_TO_CART = "ADD_ITEM_TO_CART"; 
export const REMOVE_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const ELIMINATE_FROM_CART = "ELIMINATE_PRODUCT_FROM_CART";
export const SET_TO_CART = "SET_TO_CART";